#################################################
# Makefile for JPEG4
# 2013 (C) Samsung Electronics
#################################################
CFLAGS_jpeg-regs.o := -fno-strict-aliasing
jpeg-objs := jpeg-core.o jpeg-regs.o
obj-$(CONFIG_MEDIA_EXYNOS_JPEG)	+= jpeg.o
